---
title: "COVID-19 across countries - report"
output: 
  html_document:
    theme: cosmo
    toc: true
    toc_float: true
    toc_depth: 1
    number_sections: true
params:
  countries:
    label: 'Countries (comma separated alpha-3 ISO codes)'
    value: "POL,FRA,SWE,GEO"
    input: text
  start_date:
    label: "Start date"
    value: 2020-03-01
    min: 2019-06-01
    format: "dd-mm-yyyy"
    input: date
  end_date:
    label: "End date"
    value: 2021-06-01
    min: 2019-06-02
    format: "dd-mm-yyyy"
    input: date
  measures_soc:
    label: 'Measures of socio-economic characteristics (comma separated named list WB indicators)'
    value: "NY.GDP.MKTP.CD,SH.MED.BEDS.ZS,SH.UHC.OOPC.25.TO"
    input: text
  measures_res:
    label: 'Measures of restrictions'
    value: ["stringency_index","gatherings_restrictions","international_movement_restrictions"]
    choices: ["school_closing","workplace_closing","cancel_events","gatherings_restrictions","transport_closing","stay_home_restrictions","internal_movement_restrictions","international_movement_restrictions","information_campaigns","testing_policy","contact_tracing","stringency_index"]
    multiple: TRUE
    input: select
  measures_cov:
    label: 'Measures of pandemic'
    value: ["confirmed","deaths","vaccines"]
    choices: ["confirmed","hosp","icu","vent","deaths","recovered","vaccines"]
    multiple: TRUE
    input: select
  vintage:
    label: 'Use vintage data (from End date)'
    value: FALSE
    input: checkbox
  sections:
    choices: ["Introduction","Countries' reactions","Differences in countries vs. differences in COVID","Vaccinations"]
    label: 'Sections'
    value: ["Introduction","Countries' reactions","Differences in countries vs. differences in COVID","Vaccinations"]
    multiple: TRUE
    input: select
  nclust:
    value: 2
    input: numeric
    
---

```{r chunk options, message=FALSE, warning=FALSE, include=FALSE}
knitr::opts_chunk$set(message=FALSE, warning=FALSE, echo=FALSE)
options(scipen = 999)
```

```{r load packages}
requiredPackages = c("dplyr","ggplot2","COVID19","wbstats","countrycode",
                     "tidyr","dtwclust","textshape","dendextend")
for(i in requiredPackages){if(!require(i,character.only = TRUE)) install.packages(i)}

library("dplyr","ggplot2","COVID19","wbstats")
library("countrycode")
library("tidyr")
library("dtwclust")
library("textshape")
library("dendextend")


```


```{r parse params}
# parsing parameters and creating relevant columns for subsetting data

## country
country <- strsplit(params$countries,',') %>% unlist()
country_names <- countrycode(country,'iso3c','country.name')
## restrictions
cols_res <- params$measures_res

## pandemic
cols_cov <- c(params$measures_cov,'population')

## indicators
indicators<- strsplit(params$measures_soc,',') %>% unlist()
# colnames will be set later!

```


```{r data, message=FALSE, warning=FALSE, cache=FALSE, include=FALSE}
# get wb data (looks 5 years back and chooses the latest values)
wb <- wb_data(indicators, country = country, mrv = 5, freq = 'Y', gapfill = TRUE )%>% 
  group_by(country) %>% 
  arrange(date) %>%  
  slice(n())

### delete cols with NA only (for which no data was found 5 years back)
wb <- Filter(function(x)!all(is.na(x)), wb)
### retrieve nice names of indicators and rename columns
cols_soc <- lapply(colnames(wb)[-c(1:4)], function(c) attr(wb[[c]],"label")) %>% 
  unlist()
colnames(wb)[-c(1:4)] <- cols_soc



# get covid data
data <- covid19(country = country,
                level = 1,
                start = params$start_date,
                end = params$end_date,
                vintage = params$vintage)
  
                


# join wb to covid
data <- merge(data,wb[-c(1,3,4)], by.x = 'id', by.y = 'iso3c' )

# join columns
cols_all <- c('id','date',cols_cov,cols_res,cols_soc) %>% 
  unique()
# subset data
data <- data[cols_all]

```


```{r sections to show}
# conditions for which specific sections are generated
section_intro <- ifelse('Introduction' %in% params$sections, T,F)
section_react <- ifelse("Countries' reactions" %in% params$sections & 
                  length(cols_res) > 0 & 
                  "confirmed" %in% params$measures_cov, T,F)

section_comp <- ifelse("Differences in countries vs. differences in COVID" %in% params$sections & 
                  length(cols_soc) > 0 & 
                 "confirmed" %in% params$measures_cov, T,F)

section_vacc <- ifelse("Vaccinations" %in% params$sections & 
                   "vaccines" %in% params$measures_cov  &
                 params$start_date <= '2021-01-02' &
                 params$end_date > '2021-01-02'
                 , T,F)


```



```{r introduction, eval = section_intro, child='sections/Introduction.Rmd'}

```


```{r reactions, eval = section_react, child='sections/Reactions.Rmd'}

```

```{r comparison, eval = section_comp, child='sections/Comparison.Rmd'}

```

```{r vaccines, eval = section_vacc, child='sections/Vaccines.Rmd'}

```
